# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: control.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'control.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\rcontrol.proto\x12\rvoice_control\"\xaf\x01\n\x06Intent\x12\x0c\n\x04name\x18\x01 \x01(\t\x12/\n\x05slots\x18\x02 \x03(\x0b\x32 .voice_control.Intent.SlotsEntry\x12\x10\n\x08priority\x18\x03 \x01(\x05\x12\x12\n\ndepends_on\x18\x04 \x01(\t\x12\x12\n\ntimeout_ms\x18\x05 \x01(\x03\x1a,\n\nSlotsEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\t:\x02\x38\x01\"\x86\x01\n\x15ProcessIntentsRequest\x12&\n\x07intents\x18\x01 \x03(\x0b\x32\x15.voice_control.Intent\x12*\n\x04mode\x18\x02 \x01(\x0e\x32\x1c.voice_control.ExecutionMode\x12\x19\n\x11rollback_on_error\x18\x03 \x01(\x08\"f\n\x0cIntentResult\x12\x13\n\x0bintent_name\x18\x01 \x01(\t\x12\x0f\n\x07success\x18\x02 \x01(\x08\x12\x15\n\rerror_message\x18\x03 \x01(\t\x12\x19\n\x11\x65xecution_time_ms\x18\x04 \x01(\x03\"t\n\x0bServerReply\x12\x0f\n\x07message\x18\x01 \x01(\t\x12\x0f\n\x07success\x18\x02 \x01(\x08\x12,\n\x07results\x18\x03 \x03(\x0b\x32\x1b.voice_control.IntentResult\x12\x15\n\rtotal_time_ms\x18\x04 \x01(\x03*;\n\rExecutionMode\x12\x0e\n\nSEQUENTIAL\x10\x00\x12\x0c\n\x08PARALLEL\x10\x01\x12\x0c\n\x08\x41\x44\x41PTIVE\x10\x02\x32g\n\x11\x43ommandController\x12R\n\x0eProcessIntents\x12$.voice_control.ProcessIntentsRequest\x1a\x1a.voice_control.ServerReplyb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'control_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_INTENT_SLOTSENTRY']._loaded_options = None
  _globals['_INTENT_SLOTSENTRY']._serialized_options = b'8\001'
  _globals['_EXECUTIONMODE']._serialized_start=569
  _globals['_EXECUTIONMODE']._serialized_end=628
  _globals['_INTENT']._serialized_start=33
  _globals['_INTENT']._serialized_end=208
  _globals['_INTENT_SLOTSENTRY']._serialized_start=164
  _globals['_INTENT_SLOTSENTRY']._serialized_end=208
  _globals['_PROCESSINTENTSREQUEST']._serialized_start=211
  _globals['_PROCESSINTENTSREQUEST']._serialized_end=345
  _globals['_INTENTRESULT']._serialized_start=347
  _globals['_INTENTRESULT']._serialized_end=449
  _globals['_SERVERREPLY']._serialized_start=451
  _globals['_SERVERREPLY']._serialized_end=567
  _globals['_COMMANDCONTROLLER']._serialized_start=630
  _globals['_COMMANDCONTROLLER']._serialized_end=733
# @@protoc_insertion_point(module_scope)
