# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import control_pb2 as control__pb2

GRPC_GENERATED_VERSION = '1.76.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in control_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class CommandControllerStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.ProcessIntents = channel.unary_unary(
                '/voice_control.CommandController/ProcessIntents',
                request_serializer=control__pb2.ProcessIntentsRequest.SerializeToString,
                response_deserializer=control__pb2.ServerReply.FromString,
                _registered_method=True)


class CommandControllerServicer(object):
    """Missing associated documentation comment in .proto file."""

    def ProcessIntents(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_CommandControllerServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'ProcessIntents': grpc.unary_unary_rpc_method_handler(
                    servicer.ProcessIntents,
                    request_deserializer=control__pb2.ProcessIntentsRequest.FromString,
                    response_serializer=control__pb2.ServerReply.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'voice_control.CommandController', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('voice_control.CommandController', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class CommandController(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def ProcessIntents(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/voice_control.CommandController/ProcessIntents',
            control__pb2.ProcessIntentsRequest.SerializeToString,
            control__pb2.ServerReply.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
